version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret@123
      POSTGRES_DB: FreelancingApp
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../../06-06-2025-C#-Final/Freelance-Project
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=FreelancingApp;Username=postgres;Password=secret@123"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - backend

volumes:
  postgres_data:
