version: '3.8'
services:
  webapp:
    image: httpd
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"